
event_inherited();

array = [
	"Unknown",
	"All",
	"Top",
	"Down",
	"Arm",
	"Head",
	"Chest",
	"Waist",
	"Leg",
	"Upper_arm",
	"Lower_arm",
	"Hand",
	"Skull",
	"Neck",
	"Upper_leg",
	"Lower_leg",
	"Foot",
	"Palm",
	"Finger",
	"Sole",
	"Toe",
	"Thumb",
	"Index",
	"Middle",
	"Ring",
	"Pinky",
	"Hallux",
	"Index_toe",
	"Middle_toe",
	"Ring_toe",
	"Pinky_toe",
	"First",
	"Second",
	"Third",
	]

index = 1

array_value = [
	Interhaptics_GroupID.Unknown,
	Interhaptics_GroupID.All,
	Interhaptics_GroupID.Top,
	Interhaptics_GroupID.Down,
	Interhaptics_GroupID.Arm,
	Interhaptics_GroupID.Head,
	Interhaptics_GroupID.Chest,
	Interhaptics_GroupID.Waist,
	Interhaptics_GroupID.Leg,
	Interhaptics_GroupID.Upper_arm,
	Interhaptics_GroupID.Lower_arm,
	Interhaptics_GroupID.Hand,
	Interhaptics_GroupID.Skull,
	Interhaptics_GroupID.Neck,
	Interhaptics_GroupID.Upper_leg,
	Interhaptics_GroupID.Lower_leg,
	Interhaptics_GroupID.Foot,
	Interhaptics_GroupID.Palm,
	Interhaptics_GroupID.Finger,
	Interhaptics_GroupID.Sole,
	Interhaptics_GroupID.Toe,
	Interhaptics_GroupID.Thumb,
	Interhaptics_GroupID.Index,
	Interhaptics_GroupID.Middle,
	Interhaptics_GroupID.Ring,
	Interhaptics_GroupID.Pinky,
	Interhaptics_GroupID.Hallux,
	Interhaptics_GroupID.Index_toe,
	Interhaptics_GroupID.Middle_toe,
	Interhaptics_GroupID.Ring_toe,
	Interhaptics_GroupID.Pinky_toe,
	Interhaptics_GroupID.First,
	Interhaptics_GroupID.Second,
	Interhaptics_GroupID.Third,
	]

text_group = "Group"
