
event_inherited();

array = [
	"UNKNOWN_POSITION",
	"GLOBAL",
	"RIGHT",
	"LEFT",
	"CENTER"
	]

index = 1

array_value = [
	INTERHAPTICS_LATERAL_FLAG.UNKNOWN_POSITION,
	INTERHAPTICS_LATERAL_FLAG.GLOBAL,
	INTERHAPTICS_LATERAL_FLAG.RIGHT,
	INTERHAPTICS_LATERAL_FLAG.LEFT,
	INTERHAPTICS_LATERAL_FLAG.CENTER
	]


text_group = "Side"
